# Generate the ×3 heterojunction ORBITAL line-sweep campaign — the real-orbital analog of the
# point-charge `hetsweep` (scripts/pointcharge_control.jl). Same 2-cube Si|SiO₂ junction but
# scaled ×3 (cubes 270³, slab 270×270×9), with real graphene π orbitals on the A-sublattice row
# crossing the junction (neighbor_cutoff=0 → each site's onsite U in eV). Mirrors the geometry/
# solve of scripts/gen_onsite_campaign.jl, scaled up.
#
# Run: julia --project=codes/article codes/article/sec53_lattice/scripts/gen_hetline_campaign.jl

const A1 = (2.465, 0.0)
const A2 = (-1.2325, 2.1347526)
const SUBA = (0.00093991, 0.00092506, 1)     # A sublattice (type 1)
const ZORB = 7.5
const XJUNC = 5.547
const YSLABC = 10.318

const SCALE = 3.0
const L = 90.0 * SCALE                         # cube edge / slab lateral (270)
const CZC = 3.0 - L / 2                         # cube center-z, top face at z=3 (= -132)
const MARGIN = 11.0                             # measured in-plane φ² support (~10) + buffer
const STRIDE = 3                                # subsample the lattice row → ~34 orbitals

# ×3 slab footprint (slab center (XJUNC, YSLABC, 7.5), lateral L)
const SLABX = (XJUNC - L / 2, XJUNC + L / 2)
const SLABY = (YSLABC - L / 2, YSLABC + L / 2)
const CLIPX = (SLABX[1] + MARGIN, SLABX[2] - MARGIN)
const CLIPY = (SLABY[1] + MARGIN, SLABY[2] - MARGIN)
inclip(x, y) = CLIPX[1] <= x <= CLIPX[2] && CLIPY[1] <= y <= CLIPY[2]
site(Rx, Ry) = (SUBA[1] + Rx * A1[1] + Ry * A2[1], SUBA[2] + Rx * A1[2] + Ry * A2[2])

const TEMPLATES = [
  "/mnt/ceph/users/mroesner/Graphene/cRPA4RSGW/graphene/monolayer/k_323201_nb_144_c_15/graphene_00001.xsf",
  "/mnt/ceph/users/mroesner/Graphene/cRPA4RSGW/graphene/monolayer/k_323201_nb_144_c_15/graphene_00002.xsf",
]

function line_orbitals()
    Ry = round(Int, (YSLABC - SUBA[2]) / A2[2])       # row nearest slab-center y
    orbs = Tuple{Float64,Float64}[]
    for Rx in -60:STRIDE:60
        x, y = site(Rx, Ry)
        inclip(x, y) && push!(orbs, (x, y))
    end
    sort!(orbs, by = o -> o[1])                        # left → right along x
    return orbs
end

function build_toml(name, root, orbs)
    io = IOBuffer()
    println(io, "# AUTO-GENERATED by scripts/gen_hetline_campaign.jl")
    println(io, "# ×3 heterojunction orbital line sweep: neighbor_cutoff=0 → diagonal = onsite U_i (eV).")
    println(io, "name = \"$(name)\"")
    println(io, "root = \"$(root)\"")
    println(io, "templates = [")
    for t in TEMPLATES; println(io, "  \"$(t)\","); end
    println(io, "]\n")
    for (x, y) in orbs
        println(io, "[[orbital]]")
        println(io, "type = 1")
        println(io, "x = $(x)")
        println(io, "y = $(y)")
        println(io, "z = $(ZORB)")
        println(io)
    end
    println(io, "[pairing]")
    println(io, "neighbor_cutoff = 0.0\n")
    println(io, "[dielectrics]")
    println(io, "eps_out = 1.0")
    println(io, "boxes = [")
    println(io, "  [$(XJUNC - L/2), $(YSLABC), $(CZC), $(L), $(L), $(L), 11.9],")   # Si (−x)
    println(io, "  [$(XJUNC + L/2), $(YSLABC), $(CZC), $(L), $(L), $(L), 3.9],")    # SiO₂ (+x)
    println(io, "  [$(XJUNC), $(YSLABC), 7.5, $(L), $(L), 9.0, 10.0],")            # ε=10 slab
    println(io, "]\n")
    println(io, "[solve]")
    println(io, "n_quad = 6")
    println(io, "edge_refine_level = 2")
    println(io, "rhs_tol = 1e-3")
    println(io, "lhs_tol = 1e-5")
    println(io, "gmres_rtol = 1e-5")
    println(io, "support_rtol = 1e-4")
    println(io, "volume_tol = 1e-5")
    println(io, "max_order = 8")
    println(io, "max_depth = 128\n")
    println(io, "[batching]")
    println(io, "n_centers_per_batch = 64\n")   # all ~34 orbitals in ONE batch: one shared het
                                                  # interface (~800k dof) + multi-RHS block solve
    println(io, "[eval]")
    println(io, "far_pad_steps = 2.0")
    return String(take!(io))
end

const OUTDIR = joinpath(@__DIR__, "..", "campaigns")
const CEPH = "/mnt/ceph/users/xgao1/four_index"

let orbs = line_orbitals(), nm = "onsite_hetline_3x"
    write(joinpath(OUTDIR, "$(nm).toml"), build_toml(nm, "$(CEPH)/$(nm)", orbs))
    nsi = count(o -> o[1] < XJUNC, orbs)
    println("$(nm).toml: $(length(orbs)) orbitals  (Si $(nsi) / SiO₂ $(length(orbs) - nsi)), x∈[$(round(orbs[1][1];digits=1)), $(round(orbs[end][1];digits=1))]")
end
