name = "singlecube_eps3.9"
root = "/mnt/ceph/users/xgao1/four_index/singlecube_eps3.9"
templates = ["/mnt/ceph/users/mroesner/Graphene/cRPA4RSGW/graphene/monolayer/k_323201_nb_144_c_15/graphene_00001.xsf"]

[[orbital]]
type = 1
x = 0.0
y = 0.0
z = 7.5

[pairing]
neighbor_cutoff = 0.0

[dielectrics]
eps_out = 1.0
boxes = [
  [0.0, 0.0, -42.0, 90.0, 90.0, 90.0, 3.9],
  [0.0, 0.0, 7.5, 90.0, 90.0, 9.0, 10.0],
]

[solve]
n_quad = 6
edge_refine_level = 2
rhs_tol = 1e-3
lhs_tol = 1e-5
gmres_rtol = 1e-5
support_rtol = 1e-4
volume_tol = 1e-5
max_order = 8
max_depth = 128

[batching]
n_centers_per_batch = 1

[eval]
far_pad_steps = 2.0
