# Generate the onsite-U probe campaigns for the heterojunction substrate:
#   campaigns/onsite_line.toml  — Phase 1: one graphene row across the junction (cheap pilot)
#   campaigns/onsite_grid.toml  — Phase 2: full-density lattice filling the slab
# Both use neighbor_cutoff = 0, so the assembled V is the matrix between the onsite
# densities rho_ii; its DIAGONAL V[i,i] is the screened onsite U_i. Mirrors
# campaigns/lattice_10x10_multicube.toml (identical dielectrics/solve/templates).
#
# Placement: orbitals on real graphene lattice points at z = 7.5 (slab mid-plane),
# margin-clipped so every phi^2 support stays inside the slab faces. The margin
# (11 Å) comes from the MEASURED in-plane support radius (~10 Å at support_rtol
# = 1e-4); the z half-extent (3.83 Å) clears the 4.5-Å slab faces. See
# scripts/viz_onsite_system.jl and the design spec.
#
# Run (login/workstation):
#   julia --project=codes/lattice_scale codes/lattice_scale/scripts/gen_onsite_campaign.jl

# ---- graphene lattice (same registry as lattice_10x10_multicube.toml) ----
const A1 = (2.465, 0.0)
const A2 = (-1.2325, 2.1347526)
# (origin_x, origin_y, template type) for the two sublattices
const SUBLATTICE = ((0.00093991, 0.00092506, 1), (-0.00013665, 1.42319335, 2))
const ZORB  = 7.5
const XJUNC = 5.547

# slab footprint (slab box center (5.547,10.318,7.5), size 90x90x9)
const SLABX  = (-39.453, 50.547)
const SLABY  = (-34.682, 55.318)
const YSLABC = 10.318

# margin = measured in-plane phi^2 support (~10 Å @ support_rtol=1e-4) + 1 buffer
const MARGIN = 11.0
const CLIPX  = (SLABX[1] + MARGIN, SLABX[2] - MARGIN)
const CLIPY  = (SLABY[1] + MARGIN, SLABY[2] - MARGIN)
inclip(x, y) = CLIPX[1] <= x <= CLIPX[2] && CLIPY[1] <= y <= CLIPY[2]
site(Rx, Ry, sub) = (sub[1] + Rx*A1[1] + Ry*A2[1], sub[2] + Rx*A1[2] + Ry*A2[2], sub[3])

# +x substrate cube permittivity (default SiO2 = 3.9; override e.g. SIO2_EPS=8.40)
const SIO2_EPS = parse(Float64, get(ENV, "SIO2_EPS", "3.9"))
const SUFFIX   = SIO2_EPS == 3.9 ? "" : "_eps$(SIO2_EPS)"

# Phase 2 — full-density lattice (both sublattices), margin-clipped
function grid_orbitals()
    orbs = Tuple{Int,Float64,Float64}[]   # (type, x, y)
    for Rx in -60:60, Ry in -60:60, sub in SUBLATTICE
        x, y, t = site(Rx, Ry, sub)
        inclip(x, y) && push!(orbs, (t, x, y))
    end
    sort!(orbs, by = o -> (o[3], o[2]))   # row-major for readability
    orbs
end

# Phase 1 — one A-sublattice row nearest the slab-center y, across the clipped x-range
function line_orbitals()
    subA = SUBLATTICE[1]
    Ry = round(Int, (YSLABC - subA[2]) / A2[2])
    orbs = Tuple{Int,Float64,Float64}[]
    for Rx in -80:80
        x, y, t = site(Rx, Ry, subA)
        inclip(x, y) && push!(orbs, (t, x, y))
    end
    sort!(orbs, by = o -> o[2])
    orbs
end

const TEMPLATES = [
  "/mnt/ceph/users/mroesner/Graphene/cRPA4RSGW/graphene/monolayer/k_323201_nb_144_c_15/graphene_00001.xsf",
  "/mnt/ceph/users/mroesner/Graphene/cRPA4RSGW/graphene/monolayer/k_323201_nb_144_c_15/graphene_00002.xsf",
]

function build_toml(name, root, orbs)
    io = IOBuffer()
    println(io, "# AUTO-GENERATED by scripts/gen_onsite_campaign.jl")
    println(io, "# onsite-U probe campaign: neighbor_cutoff=0 -> diagonal of V is U_i.")
    println(io, "name = \"$(name)\"")
    println(io, "root = \"$(root)\"")
    println(io, "templates = [")
    for t in TEMPLATES; println(io, "  \"$(t)\","); end
    println(io, "]\n")
    for (t, x, y) in orbs
        println(io, "[[orbital]]")
        println(io, "type = $(t)")
        println(io, "x = $(x)")
        println(io, "y = $(y)")
        println(io, "z = $(ZORB)")
        println(io)
    end
    println(io, "[pairing]")
    println(io, "neighbor_cutoff = 0.0\n")
    println(io, "[dielectrics]")
    println(io, "eps_out = 1.0")
    println(io, "boxes = [")
    println(io, "  [-39.453, 10.318, -42.0, 90.0, 90.0, 90.0, 11.9],")
    println(io, "  [50.547, 10.318, -42.0, 90.0, 90.0, 90.0, $(SIO2_EPS)],")
    println(io, "  [5.547, 10.318, 7.5, 90.0, 90.0, 9.0, 10.0],")
    println(io, "]\n")
    println(io, "[solve]")
    println(io, "n_quad = 6")
    println(io, "edge_refine_level = 2")
    println(io, "rhs_tol = 1e-3")
    println(io, "lhs_tol = 1e-5")
    println(io, "gmres_rtol = 1e-5")
    println(io, "support_rtol = 1e-4")
    println(io, "volume_tol = 1e-5")
    println(io, "max_order = 8")
    println(io, "max_depth = 128\n")
    println(io, "[batching]")
    println(io, "n_centers_per_batch = 1\n")
    println(io, "[eval]")
    println(io, "far_pad_steps = 2.0")
    return String(take!(io))
end

const OUTDIR = joinpath(@__DIR__, "..", "campaigns")
const CEPH   = "/mnt/ceph/users/xgao1/four_index"

let orbs = line_orbitals(), nm = "onsite_line$(SUFFIX)"
    write(joinpath(OUTDIR, "$(nm).toml"), build_toml(nm, "$(CEPH)/$(nm)", orbs))
    println("$(nm).toml: $(length(orbs)) orbitals  (1D row, +x cube eps=$(SIO2_EPS))")
end
let orbs = grid_orbitals(), nm = "onsite_grid$(SUFFIX)"
    nsi = count(o -> o[2] < XJUNC, orbs)
    write(joinpath(OUTDIR, "$(nm).toml"), build_toml(nm, "$(CEPH)/$(nm)", orbs))
    println("$(nm).toml: $(length(orbs)) orbitals  (Si $(nsi) / +x $(length(orbs) - nsi), +x cube eps=$(SIO2_EPS))")
end
